### ISSUE TITLE
Can you use rife without a graphics card? 

### ISSUE THREAD

**Issue by PrismFlux** [megvii-research/ECCV2022-RIFE#264]
I know its gonna be slow, but is it possible?

**Comment by prettydeep** [comment]
From inference_video.py ...

`device = torch.device("cuda" if torch.cuda.is_available() else "cpu")`

**Comment by PrismFlux** [comment]
So it uses the CPU instead, if i dont have an GPU?

**Comment by prettydeep** [comment]
Did you try to run it before asking? If it failed, what was the output?

**Comment by hzwer** [comment]
Yes, my mac laptop can run the inference code directly.
