### ISSUE TITLE
scale is a float variable not a list

### ISSUE THREAD

**Issue by NEFUJoeyChen** [megvii-research/ECCV2022-RIFE#268]
https://github.com/megvii-research/ECCV2022-RIFE/blob/337ba2a88e9a3a973eb41964f2477dacb0503e38/model/RIFE.py#L56

`    def inference(self, img0, img1, scale, TTA=False, timestep=0.5):
        scale_list = [4 / scale, 2 / scale, 1 / scale]`

This change can fix the bug

**Comment by hzwer** [comment]
Thank you very much!
