### ISSUE TITLE
插帧后的视频大小问题

### ISSUE THREAD

**Issue by sattychen** [megvii-research/ECCV2022-RIFE#270]
在用RIFE进行视频插帧时，发现一个视频大小的问题：
    原视频大小大约8M，执行 python3 inference_video.py --multi=2 --video=face_1.mp4后，输出的视频大小要到170M

    为啥会增加这么多呀？就加了一个帧，理论上不应该是增加1倍大小吗？

**Comment by YiWeiHuang-stack** [comment]
了解下视频压制

**Comment by hzwer** [comment]
RIFE 并没有为用户决定更精细的视频转码，需要用 ffmpeg 再处理一下
