### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by tralala87** [megvii-research/ECCV2022-RIFE#272]
Hi.

While running: python3 inference_video.py --exp=1 --video=video.mp4 --scale=0.5

I get:

File "C:\Users\risto\Desktop\ML-NEW\ECCV2022-RIFE-main\inference_video.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by prettydeep** [comment]
Check the requirements.txt:

opencv-python>=4.1.2

**Comment by shlurk** [comment]
I'm having the same issue, however I have the latest version of opencv-python installed and it is still showing me the same error

running:  python3 inference_video.py --exp=1 --video=video.mp4 --scale=0.5

result: File "C:\Users\anon\Desktop\Downloads\Rife\ECCV2022-RIFE-main\inference_video.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Here are some images for reference:

![image](https://user-images.githubusercontent.com/110876156/183553839-57f0f5c4-44be-4bb5-9987-ffae81c63f88.png)
![image](https://user-images.githubusercontent.com/110876156/183554064-9054c87f-d96e-4c1c-ae82-68e59845ec5b.png)

**Comment by aiac** [comment]
`pip install opencv-python`
