### ISSUE TITLE
Missing key(s) in state_dict when evaluating RIFE_HDv3 model

### ISSUE THREAD

**Issue by markdchoung** [megvii-research/ECCV2022-RIFE#273]
I am trying to evaluate RIFE_HDv3 model with Vimeo90k.
I downloaded RIFE_HDv3 model files (https://drive.google.com/file/d/1APIzVeI-4ZZCEuIRE1m6WYfSCaOsi_7_/view?usp=sharing), and I set the model in the benchmark script.
When I ran the script (Vimeo90K.py -> model changed into RIFE_HDv3),
the below errors are printed.

How can I solve this issue?

---------------------------------------------------------------------
Traceback (most recent call last):
  File "benchmark/Vimeo90K_HDv3.py", line 15, in <module>
    model.load_model('train_log')
  File "/root/workspace/sharing/ws-dongsoo/01_project/05_vfi/code/ECCV2022-RIFE/model/RIFE_HDv3.py", line 47, in load_model
    self.flownet.load_state_dict(convert(torch.load('{}/flownet.pkl'.format(path))))
  File "/root/.conda/envs/vfi_rife/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for IFNet:
        Missing key(s) in state_dict: "block0.conv0.0.0.weight", "block0.conv0.0.0.bias", "block0.conv0.0.1.weight", "block0.conv0.1.0.weight", "block0.conv0.1.0.bias", "block0.conv0.1.1.weight", "block0.convblock0.0.0.weight", "block0.convblock0.0.0.bias", "block0.convblock0.0.1.weight", "block0.convblock0.1.0.weight", "block0.convblock0.1.0.bias", "block0.convblock0.1.1.weight", "block0.convblock1.0.0.weight", "block0.convblock1.0.0.bias", "block0.convblock1.0.1.weight", "block0.convblock1.1.0.weight", "block0.convblock1.1.0.bias", "block0.convblock1.1.1.weight", "block0.convblock2.0.0.weight", "block0.convblock2.0.0.bias", "block0.convblock2.0.1.weight", "block0.convblock2.1.0.weight", "block0.convblock2.1.0.bias", "block0.convblock2.1.1.weight", "block0.convblock3.0.0.weight", "block0.convblock3.0.0.bias", "block0.convblock3.0.1.weight", "block0.convblock3.1.0.weight", "block0.convblock3.1.0.bias", "block0.convblock3.1.1.weight", "block0.conv1.0.weight", "block0.conv1.0.bias", "block0.conv1.1.weight", "block0.conv1.2.weight", "block0.conv1.2.bias", "block0.conv2.0.weight", "block0.conv2.0.bias", "block0.conv2.1.weight", "block0.conv2.2.weight", "block0.conv2.2.bias", "block1.conv0.0.0.weight", "block1.conv0.0.0.bias", "block1.conv0.0.1.weight", "block1.conv0.1.0.weight", "block1.conv0.1.0.bias", "block1.conv0.1.1.weight", "block1.convblock0.0.0.weight", "block1.convblock0.0.0.bias", "block1.convblock0.0.1.weight", "block1.convblock0.1.0.weight", "block1.convblock0.1.0.bias", "block1.convblock0.1.1.weight", "block1.convblock1.0.0.weight", "block1.convblock1.0.0.bias", "block1.convblock1.0.1.weight", "block1.convblock1.1.0.weight", "block1.convblock1.1.0.bias", "block1.convblock1.1.1.weight", "block1.convblock2.0.0.weight", "block1.convblock2.0.0.bias", "block1.convblock2.0.1.weight", "block1.convblock2.1.0.weight", "block1.convblock2.1.0.bias", "block1.convblock2.1.1.weight", "block1.convblock3.0.0.weight", "block1.convblock3.0.0.bias", "block1.convblock3.0.1.weight", "block1.convblock3.1.0.weight", "block1.convblock3.1.0.bias", "block1.convblock3.1.1.weight", "block1.conv1.0.weight", "block1.conv1.0.bias", "block1.conv1.1.weight", "block1.conv1.2.weight", "block1.conv1.2.bias", "block1.conv2.0.weight", "block1.conv2.0.bias", "block1.conv2.1.weight", "block1.conv2.2.weight", "block1.conv2.2.bias", "block2.conv0.0.0.weight", "block2.conv0.0.0.bias", "block2.conv0.0.1.weight", "block2.conv0.1.0.weight", "block2.conv0.1.0.bias", "block2.conv0.1.1.weight", "block2.convblock0.0.0.weight", "block2.convblock0.0.0.bias", "block2.convblock0.0.1.weight", "block2.convblock0.1.0.weight", "block2.convblock0.1.0.bias", "block2.convblock0.1.1.weight", "block2.convblock1.0.0.weight", "block2.convblock1.0.0.bias", "block2.convblock1.0.1.weight", "block2.convblock1.1.0.weight", "block2.convblock1.1.0.bias", "block2.convblock1.1.1.weight", "block2.convblock2.0.0.weight", "block2.convblock2.0.0.bias", "block2.convblock2.0.1.weight", "block2.convblock2.1.0.weight", "block2.convblock2.1.0.bias", "block2.convblock2.1.1.weight", "block2.convblock3.0.0.weight", "block2.convblock3.0.0.bias", "block2.convblock3.0.1.weight", "block2.convblock3.1.0.weight", "block2.convblock3.1.0.bias", "block2.convblock3.1.1.weight", "block2.conv1.0.weight", "block2.conv1.0.bias", "block2.conv1.1.weight", "block2.conv1.2.weight", "block2.conv1.2.bias", "block2.conv2.0.weight", "block2.conv2.0.bias", "block2.conv2.1.weight", "block2.conv2.2.weight", "block2.conv2.2.bias", "block_tea.conv0.0.0.weight", "block_tea.conv0.0.0.bias", "block_tea.conv0.0.1.weight", "block_tea.conv0.1.0.weight", "block_tea.conv0.1.0.bias", "block_tea.conv0.1.1.weight", "block_tea.convblock0.0.0.weight", "block_tea.convblock0.0.0.bias", "block_tea.convblock0.0.1.weight", "block_tea.convblock0.1.0.weight", "block_tea.convblock0.1.0.bias", "block_tea.convblock0.1.1.weight", "block_tea.convblock1.0.0.weight", "block_tea.convblock1.0.0.bias", "block_tea.convblock1.0.1.weight", "block_tea.convblock1.1.0.weight", "block_tea.convblock1.1.0.bias", "block_tea.convblock1.1.1.weight", "block_tea.convblock2.0.0.weight", "block_tea.convblock2.0.0.bias", "block_tea.convblock2.0.1.weight", "block_tea.convblock2.1.0.weight", "block_tea.convblock2.1.0.bias", "block_tea.convblock2.1.1.weight", "block_tea.convblock3.0.0.weight", "block_tea.convblock3.0.0.bias", "block_tea.convblock3.0.1.weight", "block_tea.convblock3.1.0.weight", "block_tea.convblock3.1.0.bias", "block_tea.convblock3.1.1.weight", "block_tea.conv1.0.weight", "block_tea.conv1.0.bias", "block_tea.conv1.1.weight", "block_tea.conv1.2.weight", "block_tea.conv1.2.bias", "block_tea.conv2.0.weight", "block_tea.conv2.0.bias", "block_tea.conv2.1.weight", "block_tea.conv2.2.weight", "block_tea.conv2.2.bias". 
        Unexpected key(s) in state_dict: "module.block0.conv0.0.0.weight", "module.block0.conv0.0.0.bias", "module.block0.conv0.0.1.weight", "module.block0.conv0.1.0.weight", "module.block0.conv0.1.0.bias", "module.block0.conv0.1.1.weight", "module.block0.convblock0.0.0.weight", "module.block0.convblock0.0.0.bias", "module.block0.convblock0.0.1.weight", "module.block0.convblock0.1.0.weight", "module.block0.convblock0.1.0.bias", "module.block0.convblock0.1.1.weight", "module.block0.convblock1.0.0.weight", "module.block0.convblock1.0.0.bias", "module.block0.convblock1.0.1.weight", "module.block0.convblock1.1.0.weight", "module.block0.convblock1.1.0.bias", "module.block0.convblock1.1.1.weight", "module.block0.convblock2.0.0.weight", "module.block0.convblock2.0.0.bias", "module.block0.convblock2.0.1.weight", "module.block0.convblock2.1.0.weight", "module.block0.convblock2.1.0.bias", "module.block0.convblock2.1.1.weight", "module.block0.convblock3.0.0.weight", "module.block0.convblock3.0.0.bias", "module.block0.convblock3.0.1.weight", "module.block0.convblock3.1.0.weight", "module.block0.convblock3.1.0.bias", "module.block0.convblock3.1.1.weight", "module.block0.conv1.0.weight", "module.block0.conv1.0.bias", "module.block0.conv1.1.weight", "module.block0.conv1.2.weight", "module.block0.conv1.2.bias", "module.block0.conv2.0.weight", "module.block0.conv2.0.bias", "module.block0.conv2.1.weight", "module.block0.conv2.2.weight", "module.block0.conv2.2.bias", "module.block1.conv0.0.0.weight", "module.block1.conv0.0.0.bias", "module.block1.conv0.0.1.weight", "module.block1.conv0.1.0.weight", "module.block1.conv0.1.0.bias", "module.block1.conv0.1.1.weight", "module.block1.convblock0.0.0.weight", "module.block1.convblock0.0.0.bias", "module.block1.convblock0.0.1.weight", "module.block1.convblock0.1.0.weight", "module.block1.convblock0.1.0.bias", "module.block1.convblock0.1.1.weight", "module.block1.convblock1.0.0.weight", "module.block1.convblock1.0.0.bias", "module.block1.convblock1.0.1.weight", "module.block1.convblock1.1.0.weight", "module.block1.convblock1.1.0.bias", "module.block1.convblock1.1.1.weight", "module.block1.convblock2.0.0.weight", "module.block1.convblock2.0.0.bias", "module.block1.convblock2.0.1.weight", "module.block1.convblock2.1.0.weight", "module.block1.convblock2.1.0.bias", "module.block1.convblock2.1.1.weight", "module.block1.convblock3.0.0.weight", "module.block1.convblock3.0.0.bias", "module.block1.convblock3.0.1.weight", "module.block1.convblock3.1.0.weight", "module.block1.convblock3.1.0.bias", "module.block1.convblock3.1.1.weight", "module.block1.conv1.0.weight", "module.block1.conv1.0.bias", "module.block1.conv1.1.weight", "module.block1.conv1.2.weight", "module.block1.conv1.2.bias", "module.block1.conv2.0.weight", "module.block1.conv2.0.bias", "module.block1.conv2.1.weight", "module.block1.conv2.2.weight", "module.block1.conv2.2.bias", "module.block2.conv0.0.0.weight", "module.block2.conv0.0.0.bias", "module.block2.conv0.0.1.weight", "module.block2.conv0.1.0.weight", "module.block2.conv0.1.0.bias", "module.block2.conv0.1.1.weight", "module.block2.convblock0.0.0.weight", "module.block2.convblock0.0.0.bias", "module.block2.convblock0.0.1.weight", "module.block2.convblock0.1.0.weight", "module.block2.convblock0.1.0.bias", "module.block2.convblock0.1.1.weight", "module.block2.convblock1.0.0.weight", "module.block2.convblock1.0.0.bias", "module.block2.convblock1.0.1.weight", "module.block2.convblock1.1.0.weight", "module.block2.convblock1.1.0.bias", "module.block2.convblock1.1.1.weight", "module.block2.convblock2.0.0.weight", "module.block2.convblock2.0.0.bias", "module.block2.convblock2.0.1.weight", "module.block2.convblock2.1.0.weight", "module.block2.convblock2.1.0.bias", "module.block2.convblock2.1.1.weight", "module.block2.convblock3.0.0.weight", "module.block2.convblock3.0.0.bias", "module.block2.convblock3.0.1.weight", "module.block2.convblock3.1.0.weight", "module.block2.convblock3.1.0.bias", "module.block2.convblock3.1.1.weight", "module.block2.conv1.0.weight", "module.block2.conv1.0.bias", "module.block2.conv1.1.weight", "module.block2.conv1.2.weight", "module.block2.conv1.2.bias", "module.block2.conv2.0.weight", "module.block2.conv2.0.bias", "module.block2.conv2.1.weight", "module.block2.conv2.2.weight", "module.block2.conv2.2.bias", "module.block_tea.conv0.0.0.weight", "module.block_tea.conv0.0.0.bias", "module.block_tea.conv0.0.1.weight", "module.block_tea.conv0.1.0.weight", "module.block_tea.conv0.1.0.bias", "module.block_tea.conv0.1.1.weight", "module.block_tea.convblock0.0.0.weight", "module.block_tea.convblock0.0.0.bias", "module.block_tea.convblock0.0.1.weight", "module.block_tea.convblock0.1.0.weight", "module.block_tea.convblock0.1.0.bias", "module.block_tea.convblock0.1.1.weight", "module.block_tea.convblock1.0.0.weight", "module.block_tea.convblock1.0.0.bias", "module.block_tea.convblock1.0.1.weight", "module.block_tea.convblock1.1.0.weight", "module.block_tea.convblock1.1.0.bias", "module.block_tea.convblock1.1.1.weight", "module.block_tea.convblock2.0.0.weight", "module.block_tea.convblock2.0.0.bias", "module.block_tea.convblock2.0.1.weight", "module.block_tea.convblock2.1.0.weight", "module.block_tea.convblock2.1.0.bias", "module.block_tea.convblock2.1.1.weight", "module.block_tea.convblock3.0.0.weight", "module.block_tea.convblock3.0.0.bias", "module.block_tea.convblock3.0.1.weight", "module.block_tea.convblock3.1.0.weight", "module.block_tea.convblock3.1.0.bias", "module.block_tea.convblock3.1.1.weight", "module.block_tea.conv1.0.weight", "module.block_tea.conv1.0.bias", "module.block_tea.conv1.1.weight", "module.block_tea.conv1.2.weight", "module.block_tea.conv1.2.bias", "module.block_tea.conv2.0.weight", "module.block_tea.conv2.0.bias", "module.block_tea.conv2.1.weight", "module.block_tea.conv2.2.weight", "module.block_tea.conv2.2.bias".

**Comment by hzwer** [comment]
You may use this code to convert the name of parameters:
https://github.com/megvii-research/ECCV2022-RIFE/blob/c6d5d702893c850e43db89ec35ca24f06db3c0a8/model/RIFE.py#L42-L47

The reason for this error is that DDP will cause the name of the saved parameter to be prefixed with "module".

**Comment by markdchoung** [comment]
It works! Thanks!
I don't know why convert function in RIFE_HDv3.py is different from the current one.

`        def convert(param):
            if rank == -1:
                return {
                    k.replace("module.", ""): v
                    for k, v in param.items()
                    if "module." in k
                }
            else:
                return param`
