### ISSUE TITLE
24fps to 60fps video?

### ISSUE THREAD

**Issue by feckpown** [megvii-research/ECCV2022-RIFE#276]
Tried the code, and it works great for converting 20fps to 60fps or 30fps 60fps. Is it possible to convert with a non-integer value, i.e. 24fps to 60fps, or 15fps to 50fps, etc? I tried:

`python3 inference_video.py --exp=1 --video=video.mp4 --fps 60 `

On the 53s@25fps demo video, but the output became a 44s@60fps, i.e. only 2x frames instead of 2.5x

**Comment by hzwer** [comment]
In principle, this can be implemented using RIFEm. But related functions currently may require you to choose packaged software, such as flowframes or SVFI.
https://github.com/megvii-research/ECCV2022-RIFE#software

**Comment by feckpown** [comment]
Thanks for the quick response! It's a pity it can't do it since it would make it tremendously much more useful. 

Would it in principle be possible to use RIFEm in Python to interpolate frames at the right points, and then simply add each new frame to a Python-OpenCV video writer? I.e., not using Flowframes or SVFI

**Comment by hzwer** [comment]
It is in principle be possible to do that. However, the encoding and decoding of the video is too complicated. For example, 24fps may not actually be an integer 24fps, and the audio before and after processing is also very difficult to align directly. So I feel that additional software support is necessary.

**Comment by feckpown** [comment]
Ok thanks for the reply :-)
