### ISSUE TITLE
Anime model request

### ISSUE THREAD

**Issue by mikebilly** [megvii-research/ECCV2022-RIFE#279]
I've always seen plenty artefacts when interpolating anime vids using rife. Could you please make a model that's specially trained on anime to create the best results for this content? Besides, rife is commonly used to interpolate anime too so I think a special model for anime would satisfy lots of people!

**Comment by hzwer** [comment]
Hi, after v4.0 model, our training set includes animation. The crux of the problem is that even though the training data is all anime, the effect is still not ideal and even worse than original version.
I know models for anime will be useful for lots of people, We're already targeting this during developing.

**Comment by mikebilly** [comment]
I see, how about a 3x interpolation dataset for animation, would that be possible to make?

**Comment by hzwer** [comment]
The question that confuses me the most is actually what dataset can improve the performance of the frame interpolation model.
In my experiments, the dataset has little effect on the performance of the frame interpolation model.
BTW, I think RIFEm can support 3x interpolation in theory.

**Comment by hzwer** [comment]
v4.4 model is specially tuned for animation, welcome to have a try.

**Comment by mikebilly** [comment]
> v4.4 model is specially tuned for animation, welcome to have a try.

Thanks for your devotion to animation, I'd love to see more development regarding animation content!

**Comment by steelywing** [comment]
I create a patch for anime, that improve a lot, see https://github.com/hzwer/Practical-RIFE/pull/23
