### ISSUE TITLE
Testtime of RIFE_m

### ISSUE THREAD

**Issue by bis70** [megvii-research/ECCV2022-RIFE#285]
How can i test the time of RIFE_m

**Comment by hzwer** [comment]
Hi, its architecture is the same as RIFE.
Did you meet any issues using this code ? https://github.com/megvii-research/ECCV2022-RIFE/blob/main/benchmark/testtime.py

**Comment by bis70** [comment]
hi, okay thank you. Is the only difference between RIFE and RIFE_m the train datset ? 

No the testtime code is okay. In my tests the result is 22ms. 

Another question, I have re-trained the NN. However, I get PSNR: 35.03db at Vimeo90k Benchmark, what could it be.

**Comment by hzwer** [comment]
Yes, the training dataset is different.

I'm not sure, what is your specific configuration. In my experiments, the vimeo90K was always at 35.5-35.6dB.
