### ISSUE TITLE
请问提供的模型_HDv3为什么没有使用融合网络呢？

### ISSUE THREAD

**Issue by sunyclj** [megvii-research/ECCV2022-RIFE#288]
您好，阅读代码发现在train_log/IFNet_HDv3.py中并没有使用论文中提到的融合网络策略，请问是基于效率考虑没有使用吗？如果加上融合网络，效率差别多少呢？不加融合网络，效果差距大吗？

**Comment by hzwer** [comment]
我们后续发现融合网络主要只是提高了 psnr，为了刷视觉效果和模型速度进行了模型合并
融合网络速度和光流网络大概是差不多的，psnr 我印象中有 0.5dB 涨幅，但是看图不明显
