### ISSUE TITLE
Result slightly diffenrent when do inference with RIFE using same images 2 times

### ISSUE THREAD

**Issue by chenyuZha** [megvii-research/ECCV2022-RIFE#290]
Hello, the mid-frame generated by RIFE is always static when we launch 2 times inference with same input images ?
Because I just did a test and realized that the result is somehow slightly different:

The image below show the heat map of `img_diff = img1 - img2`, so basically we have 2-3 pixels values diff.

![1](https://user-images.githubusercontent.com/29950360/202407071-b149b338-69d8-4f81-9f60-fe967e031665.png)
Thanks for your response!

**Comment by hzwer** [comment]
Hi, I think the result should be static.

**Comment by chenyuZha** [comment]
okay thanks for your reply!
