### ISSUE TITLE
Bug in the Google Collab

### ISSUE THREAD

**Issue by webcon1059** [megvii-research/ECCV2022-RIFE#310]
Hi. I'm not having any problems with the Google Collab, but I just want to let you know that there's a bug in it. Every time the program runs the "pip3 install -r requirements.txt" prompt, I'm shortly given an error that says Google can't find a version of torch that satisfies the requirements laid out, and it, therefore, throws off the rest of the program. I've remedied this by adding sudo pip install scikit-video before the nvida-sml line, though I thought I'd let you know about this error so you could warn others who might not know how to fix it. If you have any questions, just reply to this message. Thank You.

**Comment by hzwer** [comment]
Good job! I seemed to fix this error before, however Google continues updating the package source. I follow your solution this time. Thanks!
[fixed by this commit](https://github.com/megvii-research/ECCV2022-RIFE/commit/546a691173a689039ebbfca4a9cd5b6b4ca3555a)
