### ISSUE TITLE
关于模型训练细节问题

### ISSUE THREAD

**Issue by Liming-belief** [megvii-research/ECCV2022-RIFE#313]
你好
我尝试利用ECCV2022-RIFE/train脚本微调v4.6模型，但是生成的结果完全不如v4.6的效果。请问您在训练v4.6版本时所用的损失函数和ECCV2022-RIFE/RIFE.py中的损失函数相同吗。我观察到IFNet_HDv3在推理时fastmode=True，那么在训练时是否开启fastmode。
感谢您的回答

**Comment by hzwer** [comment]
v4.6 是基于 RIFEm 的面向应用版本
在设计面向视觉效果的模型时，我们发现了几个 trick

练时随机对图片进行 resize 2x 增广，可以改进在实用的 1080p 视频插帧效果
去掉 refinenet 主观效果更好，我们认为视觉效果可能主要取决于光流估计的稳定性和精度，这样也能使网络明显加速，训练前训练后去掉都可以
训练时间延长 4x，模型依然在涨点
Loss 选用 loss_l1 + loss_vgg

**Comment by Liming-belief** [comment]
感谢您的回答，让我收获很大，训练时随机对图片进行 resize 2x 增广是在crop之前，还是crop之后呢
