### ISSUE TITLE
[Question] Does RIFE interpolate by only using there two frames next to each other, or there are something more when Video Interpolation?

### ISSUE THREAD

**Issue by catscarlet** [megvii-research/ECCV2022-RIFE#314]
There is no discuss panel so I would just only ask a question here.

Does RIFE interpolate by only using there two frames next to each other? (Like the **Image Interpolation**)
Or there are something more when **Video Interpolation**?

------

TL;DR
Actually I just have image sequence, I want to know if there will be a difference in between 
- Convert image sequence to video and then using **RIFE Image Interpolation**
- Use **RIFE Image Interpolation** and then convert the output image sequence into video
(I already wrote shell script for iterating image sequence in folder so this won't be a problem)

**Comment by hzwer** [comment]
As long as you don't compress the video when converting to video, it won't make any difference.

**Comment by catscarlet** [comment]
> As long as you don't compress the video when converting to video, it won't make any difference.

Got it. Thank you.
