### ISSUE TITLE
如何可视化双向光流

### ISSUE THREAD

**Issue by HenrySu1145** [megvii-research/ECCV2022-RIFE#323]
作者您好，请问您是如何进行光流可视化的？ 光流只有两个通道，也不能存为RGB图。 但是在2018年CVPR SuperSloMo中他们进行彩色的可视化，而您的工作中，则是灰度图像。

**Comment by hzwer** [comment]
https://github.com/princeton-vl/RAFT/blob/master/core/utils/flow_viz.py

**Comment by HenrySu1145** [comment]
谢谢

**Comment by hzwer** [comment]
我还是不太理解，我们光流可视化都是彩色的，只是色盘有所不同而已。你说的灰度图像是 mask？
