### ISSUE TITLE
How to avoid interpolating scene changes?

### ISSUE THREAD

**Issue by hsilva664** [megvii-research/ECCV2022-RIFE#340]
Hello, I noticed that sometimes the model attempts to interpolate scene changes, which leads to bad results. This is very noticeable when watching the videos (see the example below). Simply not doing the interpolation in these cases would be enough to greatly improve results. Is there any parameter to avoid interpolation in these cases?

<div float="left">
  <img src="https://github.com/nihui/rife-ncnn-vulkan/assets/9905080/44054cc4-74ab-428c-84e3-c6c637e08d47" width="300" />
  <img src="https://github.com/nihui/rife-ncnn-vulkan/assets/9905080/6e1218d5-60fa-42d5-a8d3-2420954e9da4" width="300" /> 
  <img src="https://github.com/nihui/rife-ncnn-vulkan/assets/9905080/01a59725-56e6-4b99-b7f0-8b688a030b02" width="300" />
  <img src="https://github.com/nihui/rife-ncnn-vulkan/assets/9905080/31f5948d-7609-4b3d-892c-07400f7ccaa9" width="300" />
</div>

**Comment by hzwer** [comment]
https://github.com/megvii-research/ECCV2022-RIFE/blob/1a21b29145d2d8ac557c22ad1a156c4c4aa39348/inference_video.py#L245

The current strategy is to determine whether ssim < 0.2
This judgment can be modified according to needs

**Comment by hsilva664** [comment]
Thanks!
