### ISSUE TITLE
Training the latest model

### ISSUE THREAD

**Issue by kwu14victor** [megvii-research/ECCV2022-RIFE#345]
Hello, this is an exciting and beautifully done work! I would like to know if training the latest model (the RIFE_HDv3.py) is possible.
It seems that if I directly use the new script to replace the original model, there might be some issues when calling the update function (loss_cons is not defined).

Thank you very much for the great work and any response!

**Comment by hzwer** [comment]
https://github.com/hzwer/Practical-RIFE/blob/main/README.md#model-training

**Comment by kwu14victor** [comment]
Hi! Thanks for the response and it did help me a lot!
Thank you very much!
