### ISSUE TITLE
你好，想请教你训练UCF101的参数

### ISSUE THREAD

**Issue by RongRongRongRong** [megvii-research/ECCV2022-RIFE#348]
因为我按照Vimeo90K的参数去训练怎么都训练不出来，卡在了31左右

**Comment by hzwer** [comment]
我是用同一个模型测的，但是我有个印象是上下左右翻转能给 utf101 涨点
这个评测集质量说实话有点过时

**Comment by RongRongRongRong** [comment]
> 我是用同一个模型测的，但是我有个印象是上下左右翻转增广能给 utf101 涨点 这个评测集质量说实话有点过时

噢，好的谢谢
