### ISSUE TITLE
有关生成图片有色偏的问题

### ISSUE THREAD

**Issue by wangzf18** [megvii-research/ECCV2022-RIFE#350]
请问在做人物插帧时，生成的中间帧和原来的图片在人物皮肤上会有色偏，请问这个有什么办法解决吗，感谢！

**Comment by hzwer** [comment]
我感觉mp4变成图片再变回去就色偏了，你说的是这种情况吗？
如果不是能给个例子吗

**Comment by wangzf18** [comment]
> 我感觉有时候mp4变成图片再变回去就色偏了，你说的是这种情况吗？ 如果不是能给个例子吗

就是我把两个mp4的第一帧和最后一帧通过cv2 读出来，然后用inference img生成插帧，然后生成的插帧会和mp4中的帧序列会有偏色这样，谢谢

**Comment by hzwer** [comment]
对，那你看一下是不是读入读出那一下本身就偏色了
因为这个算法本身不太有偏色的倾向

**Comment by wangzf18** [comment]
> 对，那你看一下是不是读入读出那一下本身就偏色了 因为这个算法本身不太有偏色的倾向

哦哦好的好的，我去看看，感谢回复

**Comment by cqchenqianqc** [comment]
请问这个人物肤色这个问题，解决了吗，我也遇到相同的问题

**Comment by hzwer** [comment]
> 请问这个人物肤色这个问题，解决了吗，我也遇到相同的问题

如上所述，是 mp4 输入输出就偏色了，可能需要精细调整编解码才能和原来完全一致
