### ISSUE TITLE
您好，关于HD测试集的问题

### ISSUE THREAD

**Issue by famt0531** [megvii-research/ECCV2022-RIFE#351]
我想用您的模型观察一下HD测试集的效果，但是因为scipy版本的问题，imresize被丢弃了，无法跑通，也是因为自己python版本的问题，无法正常安装低版本的scipy。也尝试过使用别的方法去代替imresize方法，但是还是出了bug，您当时是如何做的呢

**Comment by hzwer** [comment]
我并没有遇到过类似问题。

**Comment by famt0531** [comment]
谢谢
