### ISSUE TITLE
如何启动GPU

### ISSUE THREAD

**Issue by dahuzi773** [megvii-research/ECCV2022-RIFE#360]
您好，我刚刚使用了您的这个补帧程序，效果挺赞，但是运行的时候发现负载都是CPU，GPU没运行，是否有什么参数可以设置用GPU来跑呢？我的显卡是4070，win11，感谢

**Comment by hzwer** [comment]
你好，推荐直接使用包装好的软件，[RIFE-App](https://grisk.itch.io/rife-app) | [FlowFrames](https://nmkd.itch.io/flowframes) | [SVFI (中文)](https://github.com/YiWeiHuang-stack/Squirrel-Video-Frame-Interpolation)

**Comment by dahuzi773** [comment]
> 你好，推荐直接使用包装好的软件，[RIFE-App](https://grisk.itch.io/rife-app) | [FlowFrames](https://nmkd.itch.io/flowframes) | [SVFI (中文)](https://store.steampowered.com/app/1692080/SVFI/)

感谢推荐，我也刚好找到问题了，原来是torch的版本跟我本机的cuda版本没对应上，再次谢谢您的答复和推荐
